import type { Character, MainCode, Question } from "@/types";

export const QUESTIONS: readonly [Question, Question, Question, Question] = [
  {
    id: "q1",
    axis: "SP",
    text: "로또 1등 당첨!\n어떻게 받을래?",
    a: { text: "일시불 30억(세후 15억)", emoji: "📊", value: "S" },
    b: { text: "매달 500만원 평생", emoji: "💸", value: "P" },
    ratio: { A: 52, B: 48 },
  },
  {
    id: "q2",
    axis: "EI",
    text: "모임에서 갑자기\n연봉 얘기가 나왔다!",
    a: { text: "솔직하게 말한다. 숨길 거 뭐 있어", emoji: "🗣️", value: "E" },
    b: { text: "적당히 얼버무린다. 돈은 조용히 할 일", emoji: "🤫", value: "I" },
    ratio: { A: 38, B: 62 },
  },
  {
    id: "q3",
    axis: "NR",
    text: "신이 투자 기회를 줬다.\n뭘 고를래?",
    a: { text: "3년 뒤 확정 2배", emoji: "🎯", value: "R" },
    b: { text: "50% 확률 10배, 실패하면 0원", emoji: "🎲", value: "N" },
    ratio: { A: 45, B: 55 },
  },
  {
    id: "q4",
    axis: "FL",
    text: "10억이 생겼다.\n뭘 할래?",
    a: { text: "당장 퇴사하고 하고 싶은 거 하면서 산다", emoji: "✈️", value: "F" },
    b: { text: "투자해서 더 불린다. 10억은 시작일 뿐", emoji: "💰", value: "L" },
    ratio: { A: 58, B: 42 },
  },
];

export const CHARACTERS: Record<MainCode, Character> = {
  SNF: {
    emoji: "✨",
    name: "플렉스 전략가",
    title: "계획적으로 화려하게 쓴다",
    color: "#a362ff",
    cardBg: "#4401a5",
    rarity: 8.3,
    badge: "EPIC",
    badgeColor: "#c6a2ff",
    stats: { plan: 80, invest: 70, yolo: 90 },
    oneLiner: "엑셀로 예산 짜놓고 명품 지르는 타입",
    traits: [
      { label: "계획적 지름력", value: "MAX" },
      { label: "보상소비 비중", value: "87%" },
      { label: "과시 만족도", value: "★★★★★" },
    ],
    match: { best: "SRL", worst: "PRF" },
  },
  SNL: {
    emoji: "🏗️",
    name: "자산 설계자",
    title: "시스템으로 돈을 불린다",
    color: "#49b0ff",
    cardBg: "#01599c",
    rarity: 5.1,
    badge: "EPIC",
    badgeColor: "#49b0ff",
    stats: { plan: 95, invest: 85, yolo: 20 },
    oneLiner: "자동이체 세팅하고 복리를 기다리는 타입",
    traits: [
      { label: "불필요 지출", value: "0원" },
      { label: "시스템 자동화", value: "완료" },
      { label: "현재 즐기기", value: "서툼" },
    ],
    match: { best: "PRF", worst: "PNF" },
  },
  SRF: {
    emoji: "🎯",
    name: "똑똑한 향유자",
    title: "아끼면서도 인생을 즐긴다",
    color: "#5ed0a4",
    cardBg: "#27614b",
    rarity: 14.7,
    badge: "RARE",
    badgeColor: "#b0f7cd",
    stats: { plan: 75, invest: 30, yolo: 65 },
    oneLiner: "쿠폰으로 호캉스 가는 가성비 끝판왕",
    traits: [
      { label: "가성비 스킬", value: "LV.99" },
      { label: "할인 조합력", value: "MAX" },
      { label: "삶의 질 타협", value: "불가" },
    ],
    match: { best: "PRL", worst: "SNF" },
  },
  SRL: {
    emoji: "🛡️",
    name: "철벽 수호자",
    title: "한 푼도 새어나가지 않는다",
    color: "#90d5ff",
    cardBg: "#006ec3",
    rarity: 11.2,
    badge: "RARE",
    badgeColor: "#90d5ff",
    stats: { plan: 100, invest: 40, yolo: 5 },
    oneLiner: "구독 해지할 때도 손익 계산하는 타입",
    traits: [
      { label: "충동구매 확률", value: "0%" },
      { label: "가계부 앱", value: "3개 운용" },
      { label: "자기 보상", value: "부족" },
    ],
    match: { best: "SNF", worst: "PNF" },
  },
  PNF: {
    emoji: "🔥",
    name: "본능적 투자자",
    title: "감으로 사고 감으로 판다",
    color: "#ff7472",
    cardBg: "#8f0000",
    rarity: 18.5,
    badge: "SPECIAL",
    badgeColor: "#ffd4d4",
    stats: { plan: 15, invest: 95, yolo: 85 },
    oneLiner: "코인 차트 보면서 잠드는 타입",
    traits: [
      { label: "생활비 관심도", value: "낮음" },
      { label: "최고 수익률", value: "+50%" },
      { label: "리스크 관리", value: "숙제" },
    ],
    match: { best: "SRL", worst: "PRL" },
  },
  PNL: {
    emoji: "🎰",
    name: "반전매력 재테커",
    title: "즉흥인 줄 알았지? 투자는 진지",
    color: "#ff9b4f",
    cardBg: "#9f4501",
    rarity: 4.2,
    badge: "LEGENDARY",
    badgeColor: "#ff9b4f",
    stats: { plan: 30, invest: 80, yolo: 40 },
    oneLiner: "대충 사는 것 같은데 투자 포트폴리오는 완벽",
    traits: [
      { label: "일상 소비 관심", value: "없음" },
      { label: "투자 집중도", value: "MAX" },
      { label: "소비 계획", value: "귀찮" },
    ],
    match: { best: "SRF", worst: "SRL" },
  },
  PRF: {
    emoji: "🦋",
    name: "자유로운 영혼",
    title: "돈은 쓰라고 있는 거 아닌가요?",
    color: "#ff7fca",
    cardBg: "#ad0065",
    rarity: 24.8,
    badge: "SPECIAL",
    badgeColor: "#ffb7e1",
    stats: { plan: 10, invest: 15, yolo: 100 },
    oneLiner: "카드값은 다음 달의 내가 처리해줄 거야",
    traits: [
      { label: "미래 계획", value: "내일의 나" },
      { label: "통장 확인", value: "안 봄" },
      { label: "경험 소비", value: "아끼지않음" },
    ],
    match: { best: "SNL", worst: "PNF" },
  },
  PRL: {
    emoji: "🐢",
    name: "느긋한 저축러",
    title: "급할 거 없다. 천천히 모으는 중",
    color: "#7be5d9",
    cardBg: "#2f716f",
    rarity: 13.2,
    badge: "RARE",
    badgeColor: "#a5f1e7",
    stats: { plan: 25, invest: 10, yolo: 15 },
    oneLiner: "적금 하나 넣어놓고 존재를 잊는 타입",
    traits: [
      { label: "큰 소비", value: "안 함" },
      { label: "재테크 수단", value: "적금 1개" },
      { label: "리스크 허용", value: "0%" },
    ],
    match: { best: "PNF", worst: "PRF" },
  },
};

export const SUB_TAGS: Record<"E" | "I", string> = {
  E: "돈얘기좋아하는",
  I: "조용히부자되는",
};

export const COMPAT_COMMENTS: Record<string, string> = {
  "SNF-SRL": "한 명이 지르면 한 명이 막는다. 환상의 밸런스",
  "PRF-SNL": "설계자가 자유로운 영혼을 만나면? 의외로 찰떡",
  "PNF-SNL": "시스템 vs 감각. 투자 토론 3시간 각오해",
  "PNF-SRL": "모험가와 철벽. 서로 미치겠지만 배울 게 많아",
  "PNF-PRL": "모험가와 안전주의자. 서로 배울 게 많음",
  "PRF-PRF": "둘 다 자유로운 영혼? 통장도 자유롭게 비겠다",
  "SRL-SRL": "철벽 x 철벽. 부자 될 건데 인생이 좀 심심할 수도",
  "PRF-SNF": "둘 다 쓰는 거 좋아하면... 통장이 울고 있다",
  "PRL-SRF": "둘 다 현명한 소비. 함께 가성비 맛집 투어 가자",
  "PNL-SRF": "반전 재테커와 향유자. 의외로 통하는 조합",
};

export const LOADING_TEXTS = ["돈 DNA 분석 중...", "유형 매칭 중...", "명세서 발급 중..."] as const;
